//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class KursovayaEntities1 : DbContext
    {

        private static KursovayaEntities1 _context;

        public KursovayaEntities1()
            : base("name=KursovayaEntities1")
        {
        }

        public static KursovayaEntities1 GetContext()
        {
            if (_context == null)
                _context = new KursovayaEntities1();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Информация_об_олимпиадах> Информация_об_олимпиадах { get; set; }
        public virtual DbSet<Информация_об_участниках> Информация_об_участниках { get; set; }
        public virtual DbSet<Результаты_участников> Результаты_участников { get; set; }
    }
}
