//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID_заявки { get; set; }
        public string ФИО_участника { get; set; }
        public int ID_олимпиады { get; set; }
        public string Электронная_почта { get; set; }
        public string Номер_телефона { get; set; }
    }
}
